GET {{gestion-documents-uri}}/fichier/retrieve/5c30ef2c73f382295c3e77db
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJVU0VSIl0sInN1YiI6ImhlbnJpIiwiaWF0IjoxNTQ2NzEzNTI3LCJleHAiOjE1NDY3NDIzMjd9.-b81CgNVIfjlavF4hWoi0PGG8FciJwxPunlcerRdh8F4nG7p2ylKzcLOSH1sfA3osX878FgTPXJrHeiuHwc5_g
###