POST {{host}}/{{uri-user-create}}
Content-Type: application/json

< user.json

> {%
   client.test("create user", function() {
     var status = response.status;
     var username = response.body.username;
     var enabled = response.body.enabled;

     /*assertions*/
     client.assert(status === 200, "response status is not equal to 200");
     client.assert(username === "henri", "no property id found");
     client.assert(enabled === false, "user is enabled");
   });
%}


###

GET {{host}}/{{uri-user-activate}}/{{id}}

> {%
   client.test("activate user", function() {
     var enabled = response.body.enabled;
     var status = response.status;

     /*assertions*/
     client.assert(status === 200, "response status is not equal to 200");
     client.assert(enabled === true, "user is not enbaled");
   });
 %}

###

DELETE {{host}}/{{uri-user-delete}}/{{id}}

> {%
   client.test("delete user", function() {
     var status = response.status;

     /*asserrtions*/
     client.assert(status === 200, "response status is not equal to 200")
   });
 %}
###

